SELECT * FROM T_USER WHERE NAME IS NOT NULL;
SELECT * FROM T_TICKET;

SELECT T.ID,T.DESCRIPTION,T.TDATE,T.TNUMBER FROM T_TICKET T WHERE T.TNUMBER = '123123';

UPDATE T_USER SET T_USER.ROLES='REGISTERED_USER,BOOKING_MANAGER' WHERE T_USER.NAME = 'Roma';
