--------------------------------------------------------
--  File created - Sunday-June-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_USER_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."T_USER_ACCOUNT" 
   (	"ID" NUMBER(*,0), 
	"PREPAID_AMOUNT" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index T_USER_ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."T_USER_ACCOUNT_PK" ON "SYSTEM"."T_USER_ACCOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger T_USER_ACCOUNT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."T_USER_ACCOUNT_TRG" 
BEFORE INSERT ON T_USER_ACCOUNT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT T_USER_ACCOUNT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."T_USER_ACCOUNT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table T_USER_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."T_USER_ACCOUNT" ADD CONSTRAINT "T_USER_ACCOUNT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."T_USER_ACCOUNT" MODIFY ("PREPAID_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."T_USER_ACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
